#pragma once

#include <iostream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <locale>
#include <codecvt>
#include <format>
#include <cstdint>
#include <deque>
#include <cmath>
#include <utility>
#include <random>
#include <functional>
#include <memory>
#include <fstream>
#include <streambuf>
#include <span>
#include <cstddef>
